package engine

func InitializeGraph() *Graph {
	g := &Graph{Vertices: map[string]*Vertex{}}

	g.AddVertex("Boh", "Bohemia", LandTile)
	g.AddVertex("Bud", "Budapest", LandTile)
	g.AddVertex("Gal", "Galicia", LandTile)
	g.AddVertex("Tri", "Trieste", LandTile)
	g.AddVertex("Tyr", "Tyrolia", LandTile)
	g.AddVertex("Vie", "Vienna", LandTile)
	g.AddVertex("Cly", "Clyde", LandTile)
	g.AddVertex("Edi", "Edinburgh", LandTile)
	g.AddVertex("Lvp", "Liverpool", LandTile)
	g.AddVertex("Lon", "London", LandTile)
	g.AddVertex("Wal", "Wales", LandTile)
	g.AddVertex("Yor", "Yorkshire", LandTile)
	g.AddVertex("Bre", "Brest", LandTile)
	g.AddVertex("Bur", "Burgundy", LandTile)
	g.AddVertex("Gas", "Gascony", LandTile)
	g.AddVertex("Mar", "Marseilles", LandTile)
	g.AddVertex("Par", "Paris", LandTile)
	g.AddVertex("Pic", "Picardy", LandTile)
	g.AddVertex("Ber", "Berlin", LandTile)
	g.AddVertex("Kie", "Kiel", LandTile)
	g.AddVertex("Mun", "Munich", LandTile)
	g.AddVertex("Pru", "Prussia", LandTile)
	g.AddVertex("Ruh", "Ruhr", LandTile)
	g.AddVertex("Sil", "Silesia", LandTile)
	g.AddVertex("Apu", "Apulia", LandTile)
	g.AddVertex("Nap", "Naples", LandTile)
	g.AddVertex("Pie", "Piedmont", LandTile)
	g.AddVertex("Rom", "Rome", LandTile)
	g.AddVertex("Tus", "Tuscany", LandTile)
	g.AddVertex("Ven", "Venice", LandTile)
	g.AddVertex("Fin", "Finland", LandTile)
	g.AddVertex("Lvn", "Livonia", LandTile)
	g.AddVertex("Mos", "Moscow", LandTile)
	g.AddVertex("Sev", "Sevastopol", LandTile)
	g.AddVertex("StP", "St. Petersburg", LandTile)
	g.AddVertex("Ukr", "Ukraine", LandTile)
	g.AddVertex("War", "Warsaw", LandTile)
	g.AddVertex("Ank", "Ankara", LandTile)
	g.AddVertex("Arm", "Armenia", LandTile)
	g.AddVertex("Con", "Constantinople", LandTile)
	g.AddVertex("Smy", "Smyrna", LandTile)
	g.AddVertex("Syr", "Syria", LandTile)
	g.AddVertex("Alb", "Albania", LandTile)
	g.AddVertex("Bel", "Belgium", LandTile)
	g.AddVertex("Bul", "Bulgaria", LandTile)
	g.AddVertex("Den", "Denmark", LandTile)
	g.AddVertex("Gre", "Greece", LandTile)
	g.AddVertex("Hol", "Holland", LandTile)
	g.AddVertex("Nwy", "Norway", LandTile)
	g.AddVertex("NAf", "North Africa", LandTile)
	g.AddVertex("Por", "Portugal", LandTile)
	g.AddVertex("Rum", "Rumania", LandTile)
	g.AddVertex("Ser", "Serbia", LandTile)
	g.AddVertex("Spa", "Spain", LandTile)
	g.AddVertex("Swe", "Sweden", LandTile)
	g.AddVertex("Tun", "Tunis", LandTile)
	g.AddVertex("ADR", "Adriatic Sea", WaterTile)
	g.AddVertex("AEG", "Aegean Sea", WaterTile)
	g.AddVertex("BAL", "Baltic Sea", WaterTile)
	g.AddVertex("BAR", "Barents Sea", WaterTile)
	g.AddVertex("BLA", "Black Sea", WaterTile)
	g.AddVertex("EAS", "Eastern Mediterranean", WaterTile)
	g.AddVertex("ENG", "English Channel", WaterTile)
	g.AddVertex("BOT", "Gulf of Bothnia", WaterTile)
	g.AddVertex("GOL", "Gulf of Lyon", WaterTile)
	g.AddVertex("HEL", "Helgoland Bight", WaterTile)
	g.AddVertex("ION", "Ionian Sea", WaterTile)
	g.AddVertex("IRI", "Irish Sea", WaterTile)
	g.AddVertex("MID", "Mid-Atlantic Ocean", WaterTile)
	g.AddVertex("NAT", "North Atlantic Ocean", WaterTile)
	g.AddVertex("NTH", "North Sea", WaterTile)
	g.AddVertex("NRG", "Norwegian Sea", WaterTile)
	g.AddVertex("SKA", "Skagerrak", WaterTile)
	g.AddVertex("TYN", "Tyrrhenian Sea", WaterTile)
	g.AddVertex("WES", "Western Mediterranean", WaterTile)

	return g
}
