package engine

func InitializeNewGame() *State {
	game := &State{
		Turn:  Spring,
		Phase: Order,
		Countries: [7]Country{
			Country{Name: "Austria", HomeCenters: []string{"Vie", "Bud", "Tri"}},
			Country{Name: "England", HomeCenters: []string{"Lon", "Edi", "Lvp"}},
			Country{Name: "France", HomeCenters: []string{"Par", "Mas", "Bre"}},
			Country{Name: "Germany", HomeCenters: []string{"Ber", "Mun", "Kie"}},
			Country{Name: "Italy", HomeCenters: []string{"Rom", "Ven", "Nap"}},
			Country{Name: "Russia", HomeCenters: []string{"Mos", "Sev", "War", "Stp_sc"}},
			Country{Name: "Turkey", HomeCenters: []string{"Ank", "Con", "Smy"}},
		},
		World: initializeWorld(),
	}

	return game
}

func initializeWorld() *Graph {
	g := &Graph{Vertices: map[string]*Vertex{}}

	g.AddVertex("Boh", "Bohemia", LandTile, false)
	g.AddVertex("Bud", "Budapest", LandTile, true)
	g.AddVertex("Gal", "Galicia", LandTile, false)
	g.AddVertex("Tri", "Trieste", LandTile, true)
	g.AddVertex("Tyr", "Tyrolia", LandTile, false)
	g.AddVertex("Vie", "Vienna", LandTile, true)
	g.AddVertex("Cly", "Clyde", LandTile, false)
	g.AddVertex("Edi", "Edinburgh", LandTile, true)
	g.AddVertex("Lvp", "Liverpool", LandTile, true)
	g.AddVertex("Lon", "London", LandTile, true)
	g.AddVertex("Wal", "Wales", LandTile, false)
	g.AddVertex("Yor", "Yorkshire", LandTile, false)
	g.AddVertex("Bre", "Brest", LandTile, true)
	g.AddVertex("Bur", "Burgundy", LandTile, false)
	g.AddVertex("Gas", "Gascony", LandTile, false)
	g.AddVertex("Mar", "Marseilles", LandTile, true)
	g.AddVertex("Par", "Paris", LandTile, true)
	g.AddVertex("Pic", "Picardy", LandTile, false)
	g.AddVertex("Ber", "Berlin", LandTile, true)
	g.AddVertex("Kie", "Kiel", LandTile, true)
	g.AddVertex("Mun", "Munich", LandTile, true)
	g.AddVertex("Pru", "Prussia", LandTile, false)
	g.AddVertex("Ruh", "Ruhr", LandTile, false)
	g.AddVertex("Sil", "Silesia", LandTile, false)
	g.AddVertex("Apu", "Apulia", LandTile, false)
	g.AddVertex("Nap", "Naples", LandTile, true)
	g.AddVertex("Pie", "Piedmont", LandTile, false)
	g.AddVertex("Rom", "Rome", LandTile, true)
	g.AddVertex("Tus", "Tuscany", LandTile, false)
	g.AddVertex("Ven", "Venice", LandTile, true)
	g.AddVertex("Fin", "Finland", LandTile, false)
	g.AddVertex("Lvn", "Livonia", LandTile, false)
	g.AddVertex("Mos", "Moscow", LandTile, true)
	g.AddVertex("Sev", "Sevastopol", LandTile, true)
	g.AddVertex("Stp", "St. Petersburg", LandTile, true)
	g.AddVertex("Stp_nc", "St. Petersburg (NC)", WaterTile, false)
	g.AddVertex("Stp_sc", "St. Petersburg (SC)", WaterTile, false)
	g.AddVertex("Ukr", "Ukraine", LandTile, false)
	g.AddVertex("War", "Warsaw", LandTile, true)
	g.AddVertex("Ank", "Ankara", LandTile, true)
	g.AddVertex("Arm", "Armenia", LandTile, false)
	g.AddVertex("Con", "Constantinople", LandTile, true)
	g.AddVertex("Smy", "Smyrna", LandTile, true)
	g.AddVertex("Syr", "Syria", LandTile, false)
	g.AddVertex("Alb", "Albania", LandTile, false)
	g.AddVertex("Bel", "Belgium", LandTile, true)
	g.AddVertex("Bul", "Bulgaria", LandTile, true)
	g.AddVertex("Bul_ec", "Bulgaria (EC)", WaterTile, false)
	g.AddVertex("Bul_sc", "Bulgaria (SC)", WaterTile, false)
	g.AddVertex("Den", "Denmark", LandTile, true)
	g.AddVertex("Gre", "Greece", LandTile, true)
	g.AddVertex("Hol", "Holland", LandTile, true)
	g.AddVertex("Nwy", "Norway", LandTile, true)
	g.AddVertex("Naf", "North Africa", LandTile, false)
	g.AddVertex("Por", "Portugal", LandTile, true)
	g.AddVertex("Rum", "Rumania", LandTile, true)
	g.AddVertex("Ser", "Serbia", LandTile, true)
	g.AddVertex("Spa", "Spain", LandTile, true)
	g.AddVertex("Spa_nc", "Spain (NC)", WaterTile, false)
	g.AddVertex("Spa_sc", "Spain (SC)", WaterTile, false)
	g.AddVertex("Swe", "Sweden", LandTile, true)
	g.AddVertex("Tun", "Tunis", LandTile, true)
	g.AddVertex("ADR", "Adriatic Sea", WaterTile, false)
	g.AddVertex("AEG", "Aegean Sea", WaterTile, false)
	g.AddVertex("BAL", "Baltic Sea", WaterTile, false)
	g.AddVertex("BAR", "Barents Sea", WaterTile, false)
	g.AddVertex("BLA", "Black Sea", WaterTile, false)
	g.AddVertex("EAS", "Eastern Mediterranean", WaterTile, false)
	g.AddVertex("ENG", "English Channel", WaterTile, false)
	g.AddVertex("BOT", "Gulf of Bothnia", WaterTile, false)
	g.AddVertex("LYO", "Gulf of Lyon", WaterTile, false)
	g.AddVertex("HEL", "Helgoland Bight", WaterTile, false)
	g.AddVertex("ION", "Ionian Sea", WaterTile, false)
	g.AddVertex("IRI", "Irish Sea", WaterTile, false)
	g.AddVertex("MAO", "Mid-Atlantic Ocean", WaterTile, false)
	g.AddVertex("NAO", "North Atlantic Ocean", WaterTile, false)
	g.AddVertex("NTH", "North Sea", WaterTile, false)
	g.AddVertex("NWG", "Norwegian Sea", WaterTile, false)
	g.AddVertex("SKA", "Skagerrak", WaterTile, false)
	g.AddVertex("TYS", "Tyrrhenian Sea", WaterTile, false)
	g.AddVertex("WES", "Western Mediterranean", WaterTile, false)

	g.AddEdges("Boh", []string{"Mun", "Sil", "Gal", "Vie", "Tyr"})
	g.AddEdges("Bud", []string{"Vie", "Gal", "Rum", "Ser", "Tri"})
	g.AddEdges("Gal", []string{"Boh", "Sil", "War", "Ukr", "Rum", "Bud", "Vie"})
	g.AddEdges("Tri", []string{"Ven", "Tyr", "Vie", "Bud", "Ser", "Alb", "ADR"})
	g.AddEdges("Tyr", []string{"Mun", "Boh", "Vie", "Tri", "Ven", "Pie"})
	g.AddEdges("Vie", []string{"Tyr", "Boh", "Gal", "Bud", "Tri"})
	g.AddEdges("Cly", []string{"NAO", "NWG", "Lvp", "Edi"})
	g.AddEdges("Edi", []string{"Cly", "Lvp", "NTH", "NWG", "Yor"})
	g.AddEdges("Lvp", []string{"Cly", "Edi", "IRI", "NAO", "Wal", "Yor"})
	g.AddEdges("Lon", []string{"ENG", "NTH", "Wal", "Yor"})
	g.AddEdges("Wal", []string{"ENG", "IRI", "Lon", "Lvp", "Yor"})
	g.AddEdges("Yor", []string{"Edi", "Lon", "Lvp", "NTH", "Wal"})
	g.AddEdges("Bre", []string{"ENG", "Gas", "MAO", "Par", "Pic"})
	g.AddEdges("Bur", []string{"Bel", "Gas", "Mar", "Mun", "Par", "Pic", "Ruh"})
	g.AddEdges("Gas", []string{"Bre", "Bur", "MAO", "Mar", "Par", "Spa", "Spa_nc"})
	g.AddEdges("Mar", []string{"Bur", "Gas", "LYO", "Pie", "Spa", "Spa_sc"})
	g.AddEdges("Par", []string{"Bre", "Bur", "Gas", "Pic"})
	g.AddEdges("Pic", []string{"Bel", "Bre", "Bur", "ENG", "Par"})
	g.AddEdges("Ber", []string{"BAL", "Kie", "Mun", "Pru", "Sil"})
	g.AddEdges("Kie", []string{"BAL", "Ber", "Den", "HEL", "Hol", "Mun", "Ruh"})
	g.AddEdges("Mun", []string{"Ber", "Boh", "Bur", "Kie", "Ruh", "Sil", "Tyr"})
	g.AddEdges("Pru", []string{"BAL", "Ber", "Lvn", "Sil", "War"})
	g.AddEdges("Ruh", []string{"Bel", "Bur", "Hol", "Kie", "Mun"})
	g.AddEdges("Sil", []string{"Ber", "Boh", "Gal", "Mun", "Pru", "War"})
	g.AddEdges("Apu", []string{"ADR", "ION", "Nap", "Rom", "Ven"})
	g.AddEdges("Nap", []string{"Apu", "ION", "Rom", "TYS"})
	g.AddEdges("Pie", []string{"LYO", "Mar", "Tus", "Tyr", "Ven"})
	g.AddEdges("Rom", []string{"Apu", "Nap", "TYS", "Tus", "Ven"})
	g.AddEdges("Tus", []string{"LYO", "Pie", "Rom", "TYS", "Ven"})
	g.AddEdges("Ven", []string{"ADR", "Apu", "Pie", "Rom", "Tri", "Tus", "Tyr"})
	g.AddEdges("Fin", []string{"BOT", "Nwy", "Stp", "Swe"})
	g.AddEdges("Lvn", []string{"BAL", "BOT", "Mos", "Pru", "Stp", "Stp_sc", "War"})
	g.AddEdges("Mos", []string{"Lvn", "Sev", "Stp", "Ukr", "War"})
	g.AddEdges("Sev", []string{"Arm", "BLA", "Mos", "Rum", "Ukr"})
	g.AddEdges("Stp", []string{"Stp_nc", "Stp_sc", "Fin", "Lvn", "Mos", "Nwy"})
	g.AddEdges("Stp_nc", []string{"Stp", "BAR", "Nwy"})
	g.AddEdges("Stp_sc", []string{"Stp", "BOT", "Lvn"})
	g.AddEdges("Ukr", []string{"Gal", "Mos", "Rum", "Sev", "War"})
	g.AddEdges("War", []string{"Gal", "Lvn", "Mos", "Pru", "Sil", "Ukr"})
	g.AddEdges("Ank", []string{"Arm", "BLA", "Con", "Smy"})
	g.AddEdges("Arm", []string{"Ank", "BLA", "Sev", "Smy", "Syr"})
	g.AddEdges("Con", []string{"AEG", "Ank", "BLA", "Bul", "Smy"})
	g.AddEdges("Smy", []string{"AEG", "Ank", "Arm", "Con", "EAS", "Syr"})
	g.AddEdges("Syr", []string{"Arm", "EAS", "Smy"})
	g.AddEdges("Alb", []string{"ADR", "Gre", "ION", "Ser", "Tri"})
	g.AddEdges("Bel", []string{"Bur", "ENG", "Hol", "NTH", "Pic", "Ruh"})
	g.AddEdges("Bul", []string{"Bul_ec", "Bul_sc", "Con", "Gre", "Rum", "Ser"})
	g.AddEdges("Bul_ec", []string{"BLA", "Bul", "Con", "Rum"})
	g.AddEdges("Bul_sc", []string{"AEG", "Bul", "Con", "Gre"})
	g.AddEdges("Den", []string{"BAL", "HEL", "Kie", "NTH", "SKA", "Swe"})
	g.AddEdges("Gre", []string{"AEG", "Alb", "Bul", "Bul_sc", "ION", "Ser"})
	g.AddEdges("Hol", []string{"Bel", "HEL", "Kie", "NTH", "Ruh"})
	g.AddEdges("Nwy", []string{"BAR", "Fin", "NTH", "NWG", "SKA", "Stp", "Stp_nc", "Swe"})
	g.AddEdges("Naf", []string{"MAO", "Tun", "WES"})
	g.AddEdges("Por", []string{"MAO", "Spa", "Spa_nc"})
	g.AddEdges("Rum", []string{"BLA", "Bud", "Bul", "Bul_ec", "Gal", "Ser", "Sev", "Ukr"})
	g.AddEdges("Ser", []string{"Alb", "Bud", "Bul", "Gre", "Rum", "Tri"})
	g.AddEdges("Spa", []string{"Spa_nc", "Spa_sc", "Gas", "Mar", "Por"})
	g.AddEdges("Spa_nc", []string{"MAO", "Gas", "Por", "Spa"})
	g.AddEdges("Spa_sc", []string{"MAO", "WES", "LYO", "Mar", "Spa"})
	g.AddEdges("Swe", []string{"BAL", "BOT", "Den", "Fin", "Nwy", "SKA"})
	g.AddEdges("Tun", []string{"ION", "Naf", "TYS", "WES"})
	g.AddEdges("ADR", []string{"Alb", "Apu", "ION", "Tri", "Ven"})
	g.AddEdges("AEG", []string{"BLA", "Con", "EAS", "Gre", "ION", "Smy", "Bul_sc"})
	g.AddEdges("BAL", []string{"BOT", "Ber", "Den", "Kie", "Lvn", "Pru", "SKA", "Swe"})
	g.AddEdges("BAR", []string{"NWG", "Nwy", "Stp_nc"})
	g.AddEdges("BLA", []string{"AEG", "Ank", "Arm", "Con", "Rum", "Sev", "Bul_ec"})
	g.AddEdges("EAS", []string{"AEG", "ION", "Smy", "Syr"})
	g.AddEdges("ENG", []string{"Bel", "Bre", "IRI", "Lon", "MAO", "NTH", "Pic", "Wal"})
	g.AddEdges("BOT", []string{"BAL", "Fin", "Lvn", "Swe", "Stp_sc"})
	g.AddEdges("LYO", []string{"Mar", "Pie", "TYS", "Tus", "WES", "Spa_sc"})
	g.AddEdges("HEL", []string{"Den", "Hol", "Kie", "NTH"})
	g.AddEdges("ION", []string{"ADR", "AEG", "Alb", "Apu", "EAS", "Gre", "Nap", "TYS", "Tun"})
	g.AddEdges("IRI", []string{"ENG", "Lvp", "MAO", "NAO", "Wal"})
	g.AddEdges("MAO", []string{"Bre", "ENG", "Gas", "IRI", "NAO", "Naf", "Por", "WES", "Spa_nc"})
	g.AddEdges("NAO", []string{"Cly", "IRI", "Lvp", "MAO", "NWG"})
	g.AddEdges("NTH", []string{"Bel", "Den", "ENG", "Edi", "HEL", "Hol", "Lon", "NWG", "Nwy", "SKA", "Yor"})
	g.AddEdges("NWG", []string{"BAR", "Cly", "Edi", "NAO", "NTH", "Nwy"})
	g.AddEdges("SKA", []string{"BAL", "Den", "NTH", "Nwy", "Swe"})
	g.AddEdges("TYS", []string{"ION", "LYO", "Nap", "Rom", "Tun", "Tus", "WES"})
	g.AddEdges("WES", []string{"LYO", "MAO", "Naf", "TYS", "Tun", "Spa_sc"})

	g.AddUnit("Austria", Army, "Vie")
	g.AddUnit("Austria", Army, "Bud")
	g.AddUnit("Austria", Fleet, "Tri")

	g.AddUnit("England", Fleet, "Lon")
	g.AddUnit("England", Fleet, "Edi")
	g.AddUnit("England", Army, "Lvp")

	g.AddUnit("France", Army, "Par")
	g.AddUnit("France", Army, "Mas")
	g.AddUnit("France", Fleet, "Bre")

	g.AddUnit("Germany", Army, "Ber")
	g.AddUnit("Germany", Army, "Mun")
	g.AddUnit("Germany", Fleet, "Kie")

	g.AddUnit("Italy", Army, "Rom")
	g.AddUnit("Italy", Army, "Ven")
	g.AddUnit("Italy", Fleet, "Nap")

	g.AddUnit("Russia", Army, "Mos")
	g.AddUnit("Russia", Fleet, "Sev")
	g.AddUnit("Russia", Army, "War")
	g.AddUnit("Russia", Fleet, "Stp_sc")

	g.AddUnit("Turkey", Fleet, "Ank")
	g.AddUnit("Turkey", Army, "Con")
	g.AddUnit("Turkey", Army, "Smy")

	return g
}
