package engine

func InitializeWorld() *Graph {
	g := &Graph{Vertices: map[string]*Vertex{}}

	g.AddVertex("Boh", "Bohemia", LandTile)
	g.AddVertex("Bud", "Budapest", LandTile)
	g.AddVertex("Gal", "Galicia", LandTile)
	g.AddVertex("Tri", "Trieste", LandTile)
	g.AddVertex("Tyr", "Tyrolia", LandTile)
	g.AddVertex("Vie", "Vienna", LandTile)
	g.AddVertex("Cly", "Clyde", LandTile)
	g.AddVertex("Edi", "Edinburgh", LandTile)
	g.AddVertex("Lvp", "Liverpool", LandTile)
	g.AddVertex("Lon", "London", LandTile)
	g.AddVertex("Wal", "Wales", LandTile)
	g.AddVertex("Yor", "Yorkshire", LandTile)
	g.AddVertex("Bre", "Brest", LandTile)
	g.AddVertex("Bur", "Burgundy", LandTile)
	g.AddVertex("Gas", "Gascony", LandTile)
	g.AddVertex("Mar", "Marseilles", LandTile)
	g.AddVertex("Par", "Paris", LandTile)
	g.AddVertex("Pic", "Picardy", LandTile)
	g.AddVertex("Ber", "Berlin", LandTile)
	g.AddVertex("Kie", "Kiel", LandTile)
	g.AddVertex("Mun", "Munich", LandTile)
	g.AddVertex("Pru", "Prussia", LandTile)
	g.AddVertex("Ruh", "Ruhr", LandTile)
	g.AddVertex("Sil", "Silesia", LandTile)
	g.AddVertex("Apu", "Apulia", LandTile)
	g.AddVertex("Nap", "Naples", LandTile)
	g.AddVertex("Pie", "Piedmont", LandTile)
	g.AddVertex("Rom", "Rome", LandTile)
	g.AddVertex("Tus", "Tuscany", LandTile)
	g.AddVertex("Ven", "Venice", LandTile)
	g.AddVertex("Fin", "Finland", LandTile)
	g.AddVertex("Lvn", "Livonia", LandTile)
	g.AddVertex("Mos", "Moscow", LandTile)
	g.AddVertex("Sev", "Sevastopol", LandTile)
	g.AddVertex("Stp", "St. Petersburg", LandTile)
	g.AddVertex("Ukr", "Ukraine", LandTile)
	g.AddVertex("War", "Warsaw", LandTile)
	g.AddVertex("Ank", "Ankara", LandTile)
	g.AddVertex("Arm", "Armenia", LandTile)
	g.AddVertex("Con", "Constantinople", LandTile)
	g.AddVertex("Smy", "Smyrna", LandTile)
	g.AddVertex("Syr", "Syria", LandTile)
	g.AddVertex("Alb", "Albania", LandTile)
	g.AddVertex("Bel", "Belgium", LandTile)
	g.AddVertex("Bul", "Bulgaria", LandTile)
	g.AddVertex("Den", "Denmark", LandTile)
	g.AddVertex("Gre", "Greece", LandTile)
	g.AddVertex("Hol", "Holland", LandTile)
	g.AddVertex("Nwy", "Norway", LandTile)
	g.AddVertex("Naf", "North Africa", LandTile)
	g.AddVertex("Por", "Portugal", LandTile)
	g.AddVertex("Rum", "Rumania", LandTile)
	g.AddVertex("Ser", "Serbia", LandTile)
	g.AddVertex("Spa", "Spain", LandTile)
	g.AddVertex("Swe", "Sweden", LandTile)
	g.AddVertex("Tun", "Tunis", LandTile)
	g.AddVertex("ADR", "Adriatic Sea", WaterTile)
	g.AddVertex("AEG", "Aegean Sea", WaterTile)
	g.AddVertex("BAL", "Baltic Sea", WaterTile)
	g.AddVertex("BAR", "Barents Sea", WaterTile)
	g.AddVertex("BLA", "Black Sea", WaterTile)
	g.AddVertex("EAS", "Eastern Mediterranean", WaterTile)
	g.AddVertex("ENG", "English Channel", WaterTile)
	g.AddVertex("BOT", "Gulf of Bothnia", WaterTile)
	g.AddVertex("GOL", "Gulf of Lyon", WaterTile)
	g.AddVertex("HEL", "Helgoland Bight", WaterTile)
	g.AddVertex("ION", "Ionian Sea", WaterTile)
	g.AddVertex("IRI", "Irish Sea", WaterTile)
	g.AddVertex("MID", "Mid-Atlantic Ocean", WaterTile)
	g.AddVertex("NAT", "North Atlantic Ocean", WaterTile)
	g.AddVertex("NTH", "North Sea", WaterTile)
	g.AddVertex("NRG", "Norwegian Sea", WaterTile)
	g.AddVertex("SKA", "Skagerrak", WaterTile)
	g.AddVertex("TYN", "Tyrrhenian Sea", WaterTile)
	g.AddVertex("WES", "Western Mediterranean", WaterTile)

	g.AddEdges("Boh", []string{"Mun", "Sil", "Gal", "Vie", "Tyr"})
	g.AddEdges("Bud", []string{"Vie", "Gal", "Rum", "Ser", "Tri"})
	g.AddEdges("Gal", []string{"Boh", "Sil", "War", "Ukr", "Rum", "Bud", "Vie"})
	g.AddEdges("Tri", []string{"Ven", "Tyr", "Vie", "Bud", "Ser", "Alb", "ADR"})
	g.AddEdges("Tyr", []string{"Mun", "Boh", "Vie", "Tri", "Ven", "Pie"})
	g.AddEdges("Vie", []string{"Tyr", "Boh", "Gal", "Bud", "Tri"})
	g.AddEdges("Cly", []string{"NAT", "NRG", "Lvp", "Edi"})
	g.AddEdges("Edi", []string{"Cly", "Lvp", "NTH", "NRG", "Yor"})
	g.AddEdges("Lvp", []string{"Cly", "Edi", "IRI", "NAT", "Wal", "Yor"})
	g.AddEdges("Lon", []string{"ENG", "NTH", "Wal", "Yor"})
	g.AddEdges("Wal", []string{"ENG", "IRI", "Lon", "Lvp", "Yor"})
	g.AddEdges("Yor", []string{"Edi", "Lon", "Lvp", "NTH", "Wal"})
	g.AddEdges("Bre", []string{"ENG", "Gas", "MID", "Par", "Pic"})
	g.AddEdges("Bur", []string{"Bel", "Gas", "Mar", "Mun", "Par", "Pic", "Ruh"})
	g.AddEdges("Gas", []string{"Bre", "Bur", "MID", "Mar", "Par", "Spa"})
	g.AddEdges("Mar", []string{"Bur", "Gas", "GOL", "Pie", "Spa"})
	g.AddEdges("Par", []string{"Bre", "Bur", "Gas", "Pic"})
	g.AddEdges("Pic", []string{"Bel", "Bre", "Bur", "ENG", "Par"})
	g.AddEdges("Ber", []string{"BAL", "Kie", "Mun", "Pru", "Sil"})
	g.AddEdges("Kie", []string{"BAL", "Ber", "Den", "HEL", "Hol", "Mun", "Ruh"})
	g.AddEdges("Mun", []string{"Ber", "Boh", "Bur", "Kie", "Ruh", "Sil", "Tyr"})
	g.AddEdges("Pru", []string{"BAL", "Ber", "Lvn", "Sil", "War"})
	g.AddEdges("Ruh", []string{"Bel", "Bur", "Hol", "Kie", "Mun"})
	g.AddEdges("Sil", []string{"Ber", "Boh", "Gal", "Mun", "Pru", "War"})
	g.AddEdges("Apu", []string{"ADR", "ION", "Nap", "Rom", "Ven"})
	g.AddEdges("Nap", []string{"Apu", "ION", "Rom", "TYN"})
	g.AddEdges("Pie", []string{"GOL", "Mar", "Tus", "Tyr", "Ven"})
	g.AddEdges("Rom", []string{"Apu", "Nap", "TYN", "Tus", "Ven"})
	g.AddEdges("Tus", []string{"GOL", "Pie", "Rom", "TYN", "Ven"})
	g.AddEdges("Ven", []string{"ADR", "Apu", "Pie", "Rom", "Tri", "Tus", "Tyr"})
	g.AddEdges("Fin", []string{"BOT", "Nwy", "Stp", "Swe"})
	g.AddEdges("Lvn", []string{"BAL", "BOT", "Mos", "Pru", "Stp", "War"})
	g.AddEdges("Mos", []string{"Lvn", "Sev", "Stp", "Ukr", "War"})
	g.AddEdges("Sev", []string{"Arm", "BLA", "Mos", "Rum", "Ukr"})
	g.AddEdges("Stp", []string{"Fin", "Lvn", "Mos", "Nwy"})
	g.AddEdges("Ukr", []string{"Gal", "Mos", "Rum", "Sev", "War"})
	g.AddEdges("War", []string{"Gal", "Lvn", "Mos", "Pru", "Sil", "Ukr"})
	g.AddEdges("Ank", []string{"Arm", "BLA", "Con", "Smy"})
	g.AddEdges("Arm", []string{"Ank", "BLA", "Sev", "Smy", "Syr"})
	g.AddEdges("Con", []string{"AEG", "Ank", "BLA", "Bul", "Smy"})
	g.AddEdges("Smy", []string{"AEG", "Ank", "Arm", "Con", "EAS", "Syr"})
	g.AddEdges("Syr", []string{"Arm", "EAS", "Smy"})
	g.AddEdges("Alb", []string{"ADR", "Gre", "ION", "Ser", "Tri"})
	g.AddEdges("Bel", []string{"Bur", "ENG", "Hol", "NTH", "Pic", "Ruh"})
	g.AddEdges("Bul", []string{"Bul", "Con", "Gre", "Rum", "Ser"})
	g.AddEdges("Den", []string{"BAL", "HEL", "Kie", "NTH", "SKA", "Swe"})
	g.AddEdges("Gre", []string{"AEG", "Alb", "Bul", "ION", "Ser"})
	g.AddEdges("Hol", []string{"Bel", "HEL", "Kie", "NTH", "Ruh"})
	g.AddEdges("Nwy", []string{"BAR", "Fin", "NTH", "NRG", "SKA", "Stp", "Swe"})
	g.AddEdges("Naf", []string{"MID", "Tun", "WES"})
	g.AddEdges("Por", []string{"MID", "Spa"})
	g.AddEdges("Rum", []string{"BLA", "Bud", "Bul", "Gal", "Ser", "Sev", "Ukr"})
	g.AddEdges("Ser", []string{"Alb", "Bud", "Bul", "Gre", "Rum", "Tri"})
	g.AddEdges("Spa", []string{"Gas", "Mar", "Por", "Spa"})
	g.AddEdges("Swe", []string{"BAL", "BOT", "Den", "Fin", "Nwy", "SKA"})
	g.AddEdges("Tun", []string{"ION", "Naf", "TYN", "WES"})
	g.AddEdges("ADR", []string{"Alb", "Apu", "ION", "Tri", "Ven"})
	g.AddEdges("AEG", []string{"BLA", "Con", "EAS", "Gre", "ION", "Smy"})
	g.AddEdges("BAL", []string{"BOT", "Ber", "Den", "Kie", "Lvn", "Pru", "SKA", "Swe"})
	g.AddEdges("BAR", []string{"NRG", "Nwy"})
	g.AddEdges("BLA", []string{"AEG", "Ank", "Arm", "Con", "Rum", "Sev"})
	g.AddEdges("EAS", []string{"AEG", "ION", "Smy", "Syr"})
	g.AddEdges("ENG", []string{"Bel", "Bre", "IRI", "Lon", "MID", "NTH", "Pic", "Wal"})
	g.AddEdges("BOT", []string{"BAL", "Fin", "Lvn", "Swe"})
	g.AddEdges("GOL", []string{"Mar", "Pie", "TYN", "Tus", "WES"})
	g.AddEdges("HEL", []string{"Den", "Hol", "Kie", "NTH"})
	g.AddEdges("ION", []string{"ADR", "AEG", "Alb", "Apu", "EAS", "Gre", "Nap", "TYN", "Tun"})
	g.AddEdges("IRI", []string{"ENG", "Lvp", "MID", "NAT", "Wal"})
	g.AddEdges("MID", []string{"Bre", "ENG", "Gas", "IRI", "NAT", "Naf", "Por", "WES"})
	g.AddEdges("NAT", []string{"Cly", "IRI", "Lvp", "MID", "NRG"})
	g.AddEdges("NTH", []string{"Bel", "Den", "ENG", "Edi", "HEL", "Hol", "Lon", "NRG", "Nwy", "SKA", "Yor"})
	g.AddEdges("NRG", []string{"BAR", "Cly", "Edi", "NAT", "NTH", "Nwy"})
	g.AddEdges("SKA", []string{"BAL", "Den", "NTH", "Nwy", "Swe"})
	g.AddEdges("TYN", []string{"ION", "GOL", "Nap", "Rom", "Tun", "Tus", "WES"})
	g.AddEdges("WES", []string{"GOL", "MID", "Naf", "TYN", "Tun"})

	return g
}
